update script:  * Make rlwrap optional  * Do not rely on absolute paths  * Use the rhino lib, included in the all.jar
git-svn-id: http://owltools.googlecode.com/svn/trunk@1356 18f1da76-1bb4-b526-5913-e828fe20442d

diff --git a/OWLTools-Runner/contrib/owlrhino b/OWLTools-Runner/contrib/owlrhino
--- a/OWLTools-Runner/contrib/owlrhino
+++ b/OWLTools-Runner/contrib/owlrhino
@@ -2,15 +2,24 @@
 # Set the classname of the Java class to execute
 CLASSNAME=org.mozilla.javascript.tools.shell.Main
 
-# Rhino classpath
-CLASSPATH_RHINO=$HOME/src/rhino/js.jar
+## Assumption: all classes including rhino are packed into
+## owltools-runner-all.jar
+## These will be resolved into absolute pathnames
+DEFAULT_OWLTOOLS_LOCATION=../bin/owltools-runner-all.jar
+ALTERNATIVE_OWLTOOLS_LOCATION=../owltools-runner-all.jar
 
-OBDAPI_LIB=../
-
-# Give a space-separated list of classpath items RELATIVE TO THE CURRENT SCRIPT
-# These will be resolved into absolute pathnames
-# Wildcards are allowed
-CLASSPATH_RELATIVE=../bin/owltools-runner-all.jar
+if [ -f $DEFAULT_OWLTOOLS_LOCATION ];
+then
+   CLASSPATH_RELATIVE=$DEFAULT_OWLTOOLS_LOCATION;
+else
+   if [ -f $ALTERNATIVE_OWLTOOLS_LOCATION ];
+   then
+      CLASSPATH_RELATIVE=$ALTERNATIVE_OWLTOOLS_LOCATION;
+   else
+      echo "Cannot find owltools-runner-all.jar in any of the expected locations";
+      exit 1
+   fi
+fi
 
 # If literal classpath values are needed, uncomment the line below
 # This can be useful if the classpath contains URLs
@@ -139,11 +148,15 @@ then
 	fi
 fi
 
-#echo $CLASSPATH:$CLASSPATH_RHINO
-
-[ "$1" = "-f" ] || { RLWRAP="/opt/local/bin/rlwrap -C js" ;}
-#sh -c "$JAVAPATH -Xmx1024m -classpath $CLASSPATH:$CLASSPATH_RHINO -DlauncherDir=$PATH_TO_ME $JAVAARGS $CLASSNAME $CMDARGS"
 export OWLRUNNER_SOURCE=$PATH_TO_ME/owlrunner.js
-CMD="$RLWRAP -C owlrhino $JAVAPATH -Xmx4G -classpath $CLASSPATH:$CLASSPATH_RHINO:~/bin -DlauncherDir=$PATH_TO_ME $JAVAARGS $CLASSNAME -f $PATH_TO_ME/pachyowl.js -f $PATH_TO_ME/owlrunner.js $CMDARGS -f -"
+## Construct the Java call
+CMD="$JAVAPATH -Xmx4G -classpath $CLASSPATH -DlauncherDir=$PATH_TO_ME $JAVAARGS $CLASSNAME -f $PATH_TO_ME/pachyowl.js -f $PATH_TO_ME/owlrunner.js $CMDARGS -f -"
+
+## Check for rlwrap, maintains a history and auto-completion for owlrhino
+## Do not use which, it does not set proper exit codes for errors or non-existing application
+if command -v rlwrap >/dev/null 2>&1; then
+  CMD="rlwrap -C js -C owlrhino $CMD"
+fi
+
 echo $CMD
 sh -c "$CMD"
